### ISSUE TITLE
changes to be made in ad-post page 

### ISSUE THREAD

**Issue by Satya19101996** [NicestRudeGuy/digiclassified#1]
Changes to be made in the forms    **@NicestRudeGuy** 

1. Remove Post your ad heading from the form and make it a page-header
2. Put asterisk mark in front of every required field in registration and post add form.
3. Give a label under the form Required=*
4. assign label to each field.. Right now the label is not referring to the field
5. Align *Free Listing is valid Upto 1 month to the left of the form 
6. Make button of width 100% to the form width
7. Increase column width of the form 
8. Remove the background color and border from the form 
9. Increase the height of each of the field to 35 or 40px which ever is suitable
10. Change the place holder of each field and make it start with "Enter"
11. Put column in front of each label 
12. Add an error field in front of the each field. See data-error attribute usage for this. 

Please make the changes for every form.

**Comment by NicestRudeGuy** [comment]
check commit
