### ISSUE TITLE
changes to be made in 

### ISSUE THREAD

**Issue by Satya19101996** [NicestRudeGuy/digiclassified#5]
1 Use datatable instead of table as it have pagination and sorting option 
2 Change logout background to #e36209 and text color to white 
3 Make the information boxes in the center of the container and give some color to them check bg-info color of bootstrap
4 collapsed sidebar is not working properly remove collapsing.

**Comment by NicestRudeGuy** [comment]
2.  Logout button moved to side panel 
4.  Collapsed sidebar working on all browser 
3.  Bg-info color sets light blow color to the card but it doesn't suits it

**Comment by Satya19101996** [comment]
Haven't you used datatable ?

**Comment by NicestRudeGuy** [comment]
No, test data

**Comment by Satya19101996** [comment]
Put any data and test
